"""bs-id-sequence

Revision ID: 0020
Revises: 0019
Create Date: 2025-10-22 16:31:10.131894+00:00

"""

from alembic import op
from sqlalchemy.schema import CreateSequence, DropSequence, Sequence

# revision identifiers, used by Alembic.
revision: str = "0020"
down_revision: str | None = "0019"
branch_labels: Sequence | None = None
depends_on: Sequence | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        CreateSequence(Sequence("source_id_sequence", start=2, increment=1))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        DropSequence(Sequence("source_id_sequence", start=2, increment=1))
    )
    # ### end Alembic commands ###
