user root;
daemon off;
worker_processes auto;
pid /var/snap/maas-site-manager/current/nginx.pid;
error_log stderr info;

events {
    worker_connections 768;
}

http {
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    gzip on;

    include /snap/maas-site-manager/current/etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format log_request_id '$time_iso8601 $request_id $remote_addr "$request" "$http_user_agent" $status $bytes_sent $request_time';
    access_log /var/snap/maas-site-manager/current/access.log log_request_id;

    client_body_temp_path /var/snap/maas-site-manager/current/body;
    fastcgi_temp_path /var/snap/maas-site-manager/current/fastcgi;
    proxy_temp_path /var/snap/maas-site-manager/current/proxy;
    scgi_temp_path /var/snap/maas-site-manager/current/scgi;
    uwsgi_temp_path /var/snap/maas-site-manager/current/uwsgi;

    upstream user-api {
        server unix:/var/snap/maas-site-manager/current/user-api.sock;
    }

    server {
        listen 8000;
        listen [::]:8000;

        location / {
            proxy_pass http://user-api;
            add_header X-Request-Id $request_id always;
            access_log off;
            allow 127.0.0.1;
            allow ::1;
            deny all;
        }
    }
}
